name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight
  workflow_dispatch:       # Allow running manually
  push:
    branches:
      - main               # Trigger when you push to main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: joelkkimani
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}